### ISSUE TITLE
Error importing global plugin

### ISSUE THREAD

**Issue by cartertemm** [josephsl/resourceMonitor#6] opened 2019-05-06 02:22 UTC
When building and installing the latest version, I get this.

```python
ERROR - globalPluginHandler.listPlugins (21:15:31.901):
Error importing global plugin resourceMonitor
Traceback (most recent call last):
  File "globalPluginHandler.pyo", line 22, in listPlugins
  File "addons\resourceMonitor\globalPlugins\resourceMonitor\__init__.py", line 22, in <module>
  File "addons\resourceMonitor\globalPlugins\resourceMonitor\psutilpy2\__init__.py", line 90, in <module>
ImportError: No module named _exceptions
```

**Comment by josephsl** [comment] 2019-05-06 03:52
Hi, caused by a missing file, resolved in 19.05A (plan to resolve this in source code in the next few days). Thanks for reminding me about this.

**Closed** 2019-05-20 14:26 UTC
